### ISSUE TITLE
Excel-d version upgrade?

### ISSUE THREAD

**Issue by John-Colvin** [symmetryinvestments/autowrap#94]
The version specified here tries to wrap private members, which causes compilation errors with dmd 2.087

**Comment by atilaneves** [comment]
The python code doesn't compile with dmd 2.087 either, so I'm not sure it'd help right now. Maybe an issue for dmd 2.087?
